### ISSUE TITLE
Entity Cleanup Issue

### ISSUE THREAD

**Issue by Nova3281** [Klonan/Mining_Drones#1]
It appears that when entities die they are not properly cleaned up.  I noticed  severe lag and as your mod was the last installed I removed it.  I got a lot of removed items.  I have the save if you need it.   When I reloaded the mod in after these items were cleaned up performance returned to normal.  I was getting a lot of belt deaths and I also think pathing issues caused this.  I may be able to repeat it if necessary as well.
![Error 1](https://user-images.githubusercontent.com/1025630/71013178-9aa86f80-2133-11ea-80c4-3e3778cb3baa.JPG)
![Error 2](https://user-images.githubusercontent.com/1025630/71013195-a431d780-2133-11ea-938e-2990ab0bafc3.JPG)

[WTF.zip](https://github.com/Klonan/Mining_Drones/files/3974358/WTF.zip)

**Comment by Nova3281** [comment]
I uploaded it to Google Drive.  https://drive.google.com/open?id=1xLPfpk1evKJEEA3WVMbW4ssJpmU8u4XV

**Comment by Klonan** [comment]
Oh thanks! Didn't see you make the issue here

I fixed the entity cleanup issue, there is a migration which will clean them up, and they won't be there in the future
